# Generated by Django 5.2.4 on 2025-08-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captured', '0007_alter_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='f', max_length=150),
            preserve_default=False,
        ),
    ]
