# Generated by Django 5.2.4 on 2025-08-15 19:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captured', '0008_alter_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=cloudinary.models.CloudinaryField(default='dd', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
