# Generated by Django 5.2.4 on 2025-08-15 19:12

import captured.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captured', '0009_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=captured.models.user_directory_path),
        ),
    ]
