# Generated by Django 5.2.4 on 2025-08-15 19:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captured', '0010_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=cloudinary.models.CloudinaryField(default='ss', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
